### ISSUE TITLE
Current line always displays 0 instead of absolute line number

### ISSUE THREAD

**Issue by jdluque** [jsjoeio/codemirror-line-numbers-relative#1]
Usual relative line number behavior shows the absolute line number for the line the cursor is on; however, this plugin displays 0. It would be great to see this changed to the normal behavior.

Thanks!

**Comment by jsjoeio** [comment]
Yes, you're right.

That logic lives [here](https://github.com/jsjoeio/codemirror-line-numbers-relative/blob/main/src/index.ts#L10) and [here](https://github.com/jsjoeio/codemirror-line-numbers-relative/blob/main/src/index.ts#L16).

Would you be interested in opening a PR to add this change?

**Comment by jsjoeio** [comment]
@jdluque Is this the behavior you want?

https://user-images.githubusercontent.com/3806031/148620112-af4836e9-b30a-432c-ab7e-262db218a34e.mov

I guess the better option would be to have two gutters, like VS Code does it:

![image](https://user-images.githubusercontent.com/3806031/148620303-0837d5a3-0658-4e55-b2d2-711503aa9267.png)

**Comment by jsjoeio** [comment]
There's an example in the CodeMirror docs on how to do this: https://codemirror.net/6/examples/gutter/

**Comment by jsjoeio** [comment]
https://github.com/codemirror/website/blob/master/site/examples/gutter/gutters.ts

**Comment by jdluque** [comment]
Yes, that's exactly the behavior I was referring to. I'd be happy to submit a PR. Thanks for suggesting that. 

I agree that the two gutters looks best and will have a closer look when I get a chance.
